version: '3.8'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./build:/usr/share/nginx/html
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - media_network
    depends_on:
      - db

  # certbot:
    # image: certbot/certbot
    # restart: always
    # volumes:
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # networks:
      # - media_network
  
  db:
    image: mariadb:10.11.2-jammy
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YOURROOTPASSWORD
      MYSQL_DATABASE: database-name
      MYSQL_USER: YOURUSERNAME
      MYSQL_PASSWORD: YOURPASSWORD
    volumes:
      - data:/var/lib/mysql
    networks:
      - media_network
    ports:
      - "3306:3306"
  
  backend:
    image: backend:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/database-name
      - SPRING_DATASOURCE_USERNAME=YOURUSERNAME
      - SPRING_DATASOURCE_PASSWORD=YOURPASSWORD
    networks:
      - media_network
    # volumes:
      # - /root/MediaWebApp/data/certbot/conf/live/whatsgoodie.org:/data/certbot/conf/live/whatsgoodie.org
    depends_on:
      - db

networks:
  media_network: 

volumes:
  data:
